# Generated by Django 5.2.6 on 2025-09-05 19:08

import reklam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reklam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('video', models.FileField(blank=True, null=True, upload_to=reklam.models.reklam_dosya_yolu, validators=[reklam.models.validate_gif_webp], verbose_name='Video (WEBM)')),
                ('tiklama_url', models.URLField(verbose_name='Tıklama URL')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
    ]
