# Generated by Django 5.2.6 on 2025-09-05 20:06

import reklam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Popup Adı')),
                ('video', models.FileField(blank=True, null=True, upload_to=reklam.models.popup_dosya_yolu, validators=[reklam.models.validate_gif_webp], verbose_name='Video Gif veya Webp')),
                ('tiklama_url', models.URLField(verbose_name='Tıklama URL')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
        migrations.AlterField(
            model_name='reklam',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=reklam.models.reklam_dosya_yolu, validators=[reklam.models.validate_gif_webp], verbose_name='Video Gif veya Webp'),
        ),
    ]
