# Generated by Django 5.2.6 on 2025-09-05 21:45

import reklam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklam', '0002_popup_alter_reklam_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=160)),
                ('video', models.FileField(blank=True, null=True, upload_to=reklam.models.popup_dosya_yolu, validators=[reklam.models.validate_gif_webp], verbose_name='Video Gif veya Webp')),
                ('miktar', models.CharField(default='30.000 ₺', max_length=32)),
                ('aciklama', models.CharField(default='Hoşgeldin Bonusu', max_length=120)),
                ('tiklama_url', models.URLField()),
                ('tag', models.CharField(choices=[('all', 'Tümü'), ('trend', 'Trend'), ('guncel', 'Güncel')], default='all', max_length=12)),
                ('onde', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
