# Generated by Django 5.2.6 on 2025-09-05 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklam', '0003_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
    ]
